# Generated by Django 3.2.3 on 2022-12-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteleria', '0003_auto_20221201_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteles',
            name='Medida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pasteles',
            name='Sabor',
            field=models.CharField(max_length=20),
        ),
    ]
