# Generated by Django 3.2.3 on 2022-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteleria', '0004_auto_20221201_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteles',
            name='Costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, max_length=5),
        ),
    ]
