# Generated by Django 3.2.3 on 2022-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteleria', '0005_alter_pasteles_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteles',
            name='Costo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
