# Generated by Django 3.2.3 on 2022-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteleria', '0008_alter_pasteles_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteles',
            name='Cantidad',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
