# Generated by Django 3.2.3 on 2022-12-02 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pasteleria', '0010_alter_pasteles_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasteles',
            name='Cantidad',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
