# Generated by Django 3.2.3 on 2022-11-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='Costo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
