# Generated by Django 3.2.3 on 2022-12-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizeria', '0007_alter_pizza_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='Cantidad',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
