# Generated by Django 3.2.3 on 2022-12-02 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizeria', '0008_alter_pizza_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='Cantidad',
            field=models.IntegerField(default=0, max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
