# Generated by Django 3.2.3 on 2022-12-02 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizeria', '0010_alter_pizza_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='Cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
